# .golangci.toml
#:schema https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

linters:
  exclusions:
    paths-except: ["\\./build/.*\\.go"]
  rules:
    - linters: [errcheck]
    - source: "^\\s*defer\\s+"
