---
repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        language: system
        entry: sh
        args: [-c, "cd build && exec golangci-lint run --fix"]
        types_or: [go]
        pass_filenames: false
        require_serial: true
      - id: golangci-lint-fmt
        name: golangci-lint-fmt
        language: system
        entry: sh
        args: [-c, "cd build && exec golangci-lint fmt"]
        types_or: [go]
        pass_filenames: false
        require_serial: true
