name: Build

on:
  workflow_call:
    inputs:
      container:
        type: string
        required: true
      enabled:
        type: boolean
        required: true

permissions:
  packages: write

jobs:
  build:
    if: ${{ inputs.enabled }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          sync: sshfs

          prepare: |
            set -ex

            sysctl net.inet.ip.forwarding=1

            mkdir -p /usr/local/etc/pkg/repos
            echo 'FreeBSD: { url: "pkg+https://pkg.freebsd.org/${ABI}/latest" }' > /usr/local/etc/pkg/repos/FreeBSD.conf
            pkg install -y podman-suite python3 uv

            truncate -s 32G /var/tmp/z
            mkdir -p /var/db/containers/storage
            zpool create -R /var/db/containers/storage -O mountpoint=/ -O compression=lz4 z /var/tmp/z

            buildah login -u ${{ github.actor }} -p ${{ github.token }} ghcr.io

          run: |
            set -ex
            uv run --no-build --with=pygithub --with=ruamel-yaml ./build.py '${{ inputs.container }}'
