name: Dispatch step-ca

on:
  workflow_dispatch:
    inputs:
      step-ca:
        type: boolean
        required: true
        default: false

permissions:
  packages: write

jobs:
  dispatch:
    strategy:
      matrix:
        container:
          - step-ca
      fail-fast: false
    name: ${{ matrix.container }}
    uses: ./.github/workflows/build.yaml
    with:
      container: ${{ matrix.container }}
      enabled: ${{ inputs[matrix.container] }}
