name: Dispatch amule/caddy/jdownloader/openldap/plex/qbittorrent/redis/resilio/samba-ldap/snixy

on:
  workflow_dispatch:
    inputs:
      amule:
        type: boolean
        required: true
        default: false
      caddy:
        type: boolean
        required: true
        default: false
      jdownloader:
        type: boolean
        required: true
        default: false
      openldap:
        type: boolean
        required: true
        default: false
      plex:
        type: boolean
        required: true
        default: false
      qbittorrent:
        type: boolean
        required: true
        default: false
      redis:
        type: boolean
        required: true
        default: false
      resilio:
        type: boolean
        required: true
        default: false
      samba-ldap:
        type: boolean
        required: true
        default: false
      snixy:
        type: boolean
        required: true
        default: false

permissions:
  packages: write

jobs:
  dispatch:
    strategy:
      matrix:
        container:
          - amule
          - caddy
          - jdownloader
          - openldap
          - plex
          - qbittorrent
          - redis
          - resilio
          - samba-ldap
          - snixy
      fail-fast: false
    name: ${{ matrix.container }}
    uses: ./.github/workflows/build.yaml
    with:
      container: ${{ matrix.container }}
      enabled: ${{ inputs[matrix.container] }}
