name: Dispatch

on:
  workflow_dispatch:
    inputs:
      amule:
        type: boolean
        required: true
        default: false
      caddy:
        type: boolean
        required: true
        default: false
      openldap:
        type: boolean
        required: true
        default: false
      plex:
        type: boolean
        required: true
        default: false
      qbittorrent:
        type: boolean
        required: true
        default: false
      redis:
        type: boolean
        required: true
        default: false
      resilio:
        type: boolean
        required: true
        default: false
      snixy:
        type: boolean
        required: true
        default: false
      step-ca:
        type: boolean
        required: true
        default: false

permissions:
  packages: write

jobs:
  dispatch:
    strategy:
      matrix:
        container:
          - amule
          - caddy
          - openldap
          - plex
          - qbittorrent
          - redis
          - resilio
          - snixy
          - step-ca
      fail-fast: false
    name: ${{ matrix.container }}
    uses: ./.github/workflows/build.yaml
    with:
      container: ${{ matrix.container }}
      enabled: ${{ inputs[matrix.container] }}
