name: Dispatch

on:
  workflow_dispatch:
    inputs:
      projects:
        type: string
        required: true
        default: all
      force:
        type: boolean
        required: false
        default: false

jobs:
  compute:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.compute.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Compute matrix
        id: compute
        shell: bash
        env:
          INPUT_PROJECTS: ${{ inputs.projects }}
          INPUT_FORCE: ${{ inputs.force }}
        run: |
          uv run --frozen matrix

  matrix:
    needs: [compute]
    strategy:
      matrix: ${{ fromJSON(needs.compute.outputs.matrix) }}
      fail-fast: false
    name: ${{ matrix.project }}${{ matrix.version && '-v' || '' }}${{ matrix.version }}
    uses: ./.github/workflows/project.yaml
    with:
      project: ${{ matrix.project }}
      version: ${{ matrix.version }}
      packages: ${{ matrix.packages }}
      containers: ${{ matrix.containers }}
    permissions:
      contents: write
      packages: write
