name: Dispatch

on:
  workflow_dispatch:
    inputs:
      build:
        type: choice
        default: all
        options:
          - all
          - grafana
          - openldap
          - qbittorrent
          - redis

permissions:
  packages: write

jobs:
  dispatch:
    strategy:
      matrix:
        container:
          - name: grafana
            packages: grafana
            user: grafana:grafana
            entrypoint: /usr/local/bin/grafana
          - name: openldap
            packages: FreeBSD-libsqlite3 openldap26-server
            entrypoint: /usr/local/libexec/slapd
          - name: qbittorrent
            base: freebsd:small
            platforms: freebsd/amd64
            packages: qbittorrent-nox
            user: qbittorrent:qbittorrent
            entrypoint: /usr/local/bin/qbittorrent-nox
          - name: redis
            packages: redis
            entrypoint: /usr/local/bin/redis-server
    name: ${{ matrix.container.name }}
    uses: ./.github/workflows/build.yaml
    with:
      container: ${{ toJSON(matrix.container) }}
      build: ${{ inputs.build }}
