name: Dispatch

on:
  workflow_dispatch:
    inputs:
      build:
        type: choice
        default: all
        options:
          - all
          - caddy
          - grafana
          - openldap
          - qbittorrent
          - redis
          - resilio

permissions:
  packages: write

jobs:
  dispatch:
    strategy:
      matrix:
        container:
          - name: caddy
            tarball: https://github.com/caddyserver/caddy/releases/download/v2.8.4/caddy_2.8.4_freebsd_{arch}.tar.gz#caddy
          - name: grafana
            pkg: grafana
            user: grafana:grafana
            entrypoint: /usr/local/bin/grafana
          - name: openldap
            pkg: FreeBSD-libsqlite3 openldap26-server
            entrypoint: /usr/local/libexec/slapd
          - name: qbittorrent
            base: freebsd:small
            arch: amd64
            pkg: qbittorrent-nox
            user: qbittorrent:qbittorrent
            entrypoint: /usr/local/bin/qbittorrent-nox
          - name: redis
            pkg: redis
            user: redis:redis
            entrypoint: /usr/local/bin/redis-server
          - name: resilio
            base: freebsd:base
            arch: amd64
            tarball: https://download-cdn.resilio.com/2.8.1.1390/freebsd/x64/0/resilio-sync_freebsd_x64.tar.gz#rslsync
            user: '851:851'
    name: ${{ matrix.container.name }}
    uses: ./.github/workflows/build.yaml
    with:
      container: ${{ toJSON(matrix.container) }}
      build: ${{ inputs.build }}
