name: Packages

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
      version:
        type: string
        required: true
      packages:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(inputs.packages) }}
    name: build (${{ matrix.package }})
    steps:
      - name: Free disk space
        if: false && (matrix.builder == 'cgo' || matrix.builder == 'uv')
        uses: mathio/gha-cleanup@v1
        with:
          remove-browsers: true
          verbose: true

      - name: Checkout
        uses: actions/checkout@v5

      - name: Checkout ${{ matrix.repo }} @ ${{ matrix.ref }}
        uses: actions/checkout@v5
        with:
          repository: ${{ matrix.repo }}
          ref: ${{ matrix.ref }}
          path: src

      - name: Setup uv
        if: matrix.builder != 'uv'
        uses: astral-sh/setup-uv@v7

      - name: Setup go
        if: matrix.builder == 'go'
        uses: actions/setup-go@v6
        with:
          go-version: stable
          check-latest: true

      - name: Setup goreleaser
        if: matrix.builder == 'go'
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          install-only: true

      - name: Build
        if: matrix.builder != 'uv'
        shell: bash
        env:
          INPUT_PROJECT: ${{ inputs.project }}
          INPUT_VERSION: ${{ inputs.version }}
          INPUT_PACKAGE: ${{ matrix.package }}
        run: |
          env PYTHONUNBUFFERED=1 uv run --frozen build-package

      - name: Build with VM
        if: matrix.builder == 'uv'
        uses: acj/freebsd-firecracker-action@v0.6.0
        with:
          checkout: false
          disk-size: 20G
          pre-run: |
            rsync --links --recursive --relative . firecracker:
          run-in-vm: |
            .github/scripts/setup-freebsd.sh package

            env \
              INPUT_PROJECT="${{ inputs.project }}" \
              INPUT_VERSION="${{ inputs.version }}" \
              INPUT_PACKAGE="${{ matrix.package }}" \
              PATH="/root/bin:$PATH" \
              PYTHONUNBUFFERED=1 \
              uv run --frozen build-package
          post-run: |
            rsync --links --recursive --relative firecracker:dist dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.project }}#${{ matrix.package }}
          path: dist/${{ matrix.package }}-*
          compression-level: 0
          if-no-files-found: error
          retention-days: 1

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: ${{ inputs.project }}#*
          path: ./dist/
          merge-multiple: true

      - name: Create release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ inputs.project }}-v${{ inputs.version }}
        run: |
          shopt -s nullglob

          for i in dist/*.whl; do
            i=$(basename "$i")
            echo "<a href=\"https://github.com/cynix/freebsd-binaries/releases/download/$TAG/$i\">$i</a><br>" >> dist/wheels.html
          done

          echo "Deleting existing $TAG"
          gh release delete --cleanup-tag --yes $TAG || true

          echo "Releasing $TAG"
          gh release create --latest=true --notes=$TAG --title=$TAG $TAG ./dist/*

          for i in $(gh release list --json=tagName --jq="map(select(.tagName | startswith(\"${{ inputs.project }}-\")))[3:] | .[].tagName"); do
            echo "Deleting $i"
            gh release delete --cleanup-tag --yes $i || echo "Could not delete $i"
          done
